sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
matrix:
  include:
    - python: "2.7"
      env: TOXENV=perf

before_install: |
  pip install tox
  if [ ! -v TOXENV ]
  then
    __py_ver=$TRAVIS_PYTHON_VERSION
    __tox_dfl=${__py_ver/[0-9].[0-9]/py${__py_ver/.}}
    export TOXENV=${TOXENV:-$__tox_dfl}
  fi
  function announce()
    { echo -e "$ANSI_GREEN$@${ANSI_RESET}"; }
  function tox()
    { announce "Running tox in TOXENV=$TOXENV"; env tox "$@"; }

install: tox --notest
script: tox

cache:
  directories:
    - $HOME/.cache/pip/http
